version: '3.8'

services:
  app:
    image: saugatadey98/quizappaugust:0.0.1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/questiondb

    depends_on:
      - db

  db:
    image: "postgres:15-alpine3.17"
    ports:
      - "5432:5432"
    environment:
      DATABASE_PORT: 5432
      POSTGRES_DB: questiondb
      POSTGRES_USER: questiondb
      POSTGRES_PASSWORD: Saugata@1998